### ISSUE TITLE
Realm: Crash when a new user login

### ISSUE THREAD

**Issue by phamhongphuc** [phamhongphuc/uit.money#2]
If a client call `.findAllAsync()` when the schema hasn't created yet the application will crash

```
E/REALM_JNI: jni: ThrowingException 8, Cannot create asynchronous query while in a write transaction in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_sync_OsSubscription.cpp line 71, .
             Exception has been thrown: Cannot create asynchronous query while in a write transaction in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_sync_OsSubscription.cpp line 71
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: uit.money, PID: 12710
                  java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_sync_OsSubscription.cpp line 71
                      at io.realm.internal.sync.OsSubscription.nativeStartListening(Native Method)
                      at io.realm.internal.sync.OsSubscription.addChangeListener(OsSubscription.java:101)
                      at io.realm.internal.SubscriptionAwareOsResults.<init>(SubscriptionAwareOsResults.java:54)
                      at io.realm.internal.SubscriptionAwareOsResults.createFromQuery(SubscriptionAwareOsResults.java:46)
                      at io.realm.RealmQuery.createRealmResults(RealmQuery.java:2014)
                      at io.realm.RealmQuery.findAllAsync(RealmQuery.java:1783)
                      at model.model.Wallet.autoId(Wallet.java:109)
                      at model.model.Wallet.lambda$createEmptyWallet$0$Wallet(Wallet.java:71)
                      at model.model.Wallet$$Lambda$0.call(Unknown Source)
                      at model.model.Wallet.<init>(Wallet.java:49)
                      at model.model.Wallet.createEmptyWallet(Wallet.java:70)
                      at model.model.Wallet.getCurrentWallet(Wallet.java:60)
                      at uit.money.activity.LoginActivity.lambda$initializeListener$0$LoginActivity(LoginActivity.java:39)
                      at uit.money.activity.LoginActivity$$Lambda$0.call(Unknown Source)
                      at uit.money.facebook.Credential.lambda$checkAndLogin$0$Credential(Credential.java:46)
                      at uit.money.facebook.Credential$$Lambda$0.call(Unknown Source)
                      at uit.money.facebook.Credential$2.onSuccess(Credential.java:62)
                      at uit.money.facebook.Credential$2.onSuccess(Credential.java:52)
                      at io.realm.SyncUser$Request$3.run(SyncUser.java:695)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
![image](https://user-images.githubusercontent.com/11532116/39671698-d5843138-5147-11e8-82e3-cb17feef1d9f.png)

**Comment by phamhongphuc** [comment]
Resolved: realm/realm-java#4974

> That is an restriction of adding listeners.
> Please just move RealmResults.addChangeListerner() out of the transaction block.
